FROM node:latest
WORKDIR /app

COPY package*.json ./

RUN npm install
COPY . .

ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV CLERK_SECRET_KEY=$CLERK_SECRET_KEY

RUN npm run build

EXPOSE 3000


CMD ["npm","run","start"]