name: Build in PR

on:
  push:
   branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Setting Up Machine
         uses: actions/setup-node@v3
         with:
           node-version: "20"

       - name: Installing Dependencies
         run: npm install

       - name: Building the Project
         run: npm run build
