name: "Deploying..."

on:
  push:
    branches:
      - main

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Setting Up Machine
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: bikaxh01/pdf-chat:latest  
    
    - name: Pulling Image
      run : docker pull bikaxh01/pdf-chat:latest 